import { FileText, FileSpreadsheet, Presentation, FileCode, FileImage, Download, Package } from "lucide-react";
import { AppLayout } from "../components/layout/AppLayout";
import { Card, CardHeader } from "../components/ui/Card";
import { Badge } from "../components/ui/Badge";
import { EmptyState } from "../components/ui/EmptyState";
import { api } from "../lib/api";
import { usePoll } from "../lib/usePoll";

const ICONS: Record<string, typeof FileText> = {
  docx: FileText,
  xlsx: FileSpreadsheet,
  pptx: Presentation,
  code: FileCode,
  pdf: FileImage,
};

const TONE: Record<string, "blue" | "green" | "amber" | "teal" | "red"> = {
  docx: "blue",
  xlsx: "green",
  pptx: "amber",
  code: "teal",
  pdf: "red",
};

export default function Outputs() {
  const { data: deliverables, loading } = usePoll(() => api.outputs.list(), 4000);

  return (
    <AppLayout title="Deliverables" subtitle="Real artifacts, not chat replies — generated by completed agent tasks">
      <div className="p-6">
        <Card>
          <CardHeader title="Generated artifacts" subtitle="Live — populated as agent tasks complete" />
          {loading && !deliverables ? (
            <div className="p-5 text-[12px] text-[var(--color-ink-faint)]">Loading…</div>
          ) : deliverables && deliverables.length > 0 ? (
            <div className="divide-y divide-[var(--color-border-soft)]">
              {deliverables.map((d: any) => {
                const Icon = ICONS[d.kind] ?? FileText;
                return (
                  <div key={d.id} className="flex items-center gap-4 px-5 py-4">
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-white/[0.03]">
                      <Icon className="h-[18px] w-[18px] text-[var(--color-ink-dim)]" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="truncate text-[13px] font-medium text-white">{d.name}</div>
                      <div className="mt-0.5 text-[11.5px] text-[var(--color-ink-faint)]">task {d.task_id?.slice(0, 8)}</div>
                    </div>
                    <div className="hidden text-right sm:block">
                      <div className="text-[11.5px] text-[var(--color-ink-dim)]">{new Date(d.created_at * 1000).toLocaleString()}</div>
                      <div className="mono text-[10.5px] text-[var(--color-ink-faint)]">{d.size_kb} KB · {d.source_model}</div>
                    </div>
                    <Badge tone={TONE[d.kind] ?? "neutral"}>{d.kind}</Badge>
                    <a
                      href={api.outputs.downloadUrl(d.id)}
                      className="flex h-8 w-8 items-center justify-center rounded-md border border-[var(--color-border)] text-[var(--color-ink-dim)] hover:text-white"
                    >
                      <Download className="h-3.5 w-3.5" />
                    </a>
                  </div>
                );
              })}
            </div>
          ) : (
            <EmptyState
              icon={<Package className="h-5 w-5" />}
              title="No deliverables generated yet"
              detail="Run a task in the Workspace that produces a document — it will appear here automatically."
            />
          )}
        </Card>
      </div>
    </AppLayout>
  );
}
